//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelfFinanceManagerUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SelfFinanceManagerUI.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be less than {1}.
        /// </summary>
        public static string _0__cannot_be_less_than__1_ {
            get {
                return ResourceManager.GetString("{0} cannot be less than {1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred. This application may no longer respond until reloaded..
        /// </summary>
        public static string An_error_has_occurred__This_application_may_no_longer_respond_until_reloaded_ {
            get {
                return ResourceManager.GetString("An error has occurred. This application may no longer respond until reloaded.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string An_error_occurred_while_processing_your_request_ {
            get {
                return ResourceManager.GetString("An error occurred while processing your request.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has occurred. See browser dev tools for details..
        /// </summary>
        public static string An_unhandled_exception_has_occurred__See_browser_dev_tools_for_details_ {
            get {
                return ResourceManager.GetString("An unhandled exception has occurred. See browser dev tools for details.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name already exists..
        /// </summary>
        public static string CategoryNameExists {
            get {
                return ResourceManager.GetString("CategoryNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category name must be between 2 and 50 characters..
        /// </summary>
        public static string CategoryNameLength {
            get {
                return ResourceManager.GetString("CategoryNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is required..
        /// </summary>
        public static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be in the future..
        /// </summary>
        public static string Date_cannot_be_in_the_future_ {
            get {
                return ResourceManager.GetString("Date cannot be in the future.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining session state, please wait....
        /// </summary>
        public static string Determining_session_state__please_wait___ {
            get {
                return ResourceManager.GetString("Determining session state, please wait...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Mode.
        /// </summary>
        public static string Development_Mode {
            get {
                return ResourceManager.GetString("Development Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date (optional).
        /// </summary>
        public static string End_Date__optional_ {
            get {
                return ResourceManager.GetString("End Date (optional)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount.
        /// </summary>
        public static string Enter_amount {
            get {
                return ResourceManager.GetString("Enter amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter category name.
        /// </summary>
        public static string Enter_category_name {
            get {
                return ResourceManager.GetString("Enter category name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        public static string Enter_name {
            get {
                return ResourceManager.GetString("Enter name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new category name.
        /// </summary>
        public static string Enter_new_category_name {
            get {
                return ResourceManager.GetString("Enter new category name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app..
        /// </summary>
        public static string For_local_debugging__enable_the_Development_environment_by_setting_the_ASPNETCORE_ENVIRONMENT_environment_variable_to_Development_and_restarting_the_app_ {
            get {
                return ResourceManager.GetString("For local debugging, enable the Development environment by setting the ASPNETCORE" +
                        "_ENVIRONMENT environment variable to Development and restarting the app.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can result in displaying sensitive information from exceptions to end users..
        /// </summary>
        public static string It_can_result_in_displaying_sensitive_information_from_exceptions_to_end_users_ {
            get {
                return ResourceManager.GetString("It can result in displaying sensitive information from exceptions to end users.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data, please wait....
        /// </summary>
        public static string Loading_data__please_wait___ {
            get {
                return ResourceManager.GetString("Loading data, please wait...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string New_Category {
            get {
                return ResourceManager.GetString("New Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Operation.
        /// </summary>
        public static string New_Operation {
            get {
                return ResourceManager.GetString("New Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operations found for this category..
        /// </summary>
        public static string No_operations_found_for_this_category_ {
            get {
                return ResourceManager.GetString("No operations found for this category.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operations found for this date..
        /// </summary>
        public static string No_operations_found_for_this_date_ {
            get {
                return ResourceManager.GetString("No operations found for this date.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string Not_found {
            get {
                return ResourceManager.GetString("Not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than 0.
        /// </summary>
        public static string OperationAmountOutOfRange {
            get {
                return ResourceManager.GetString("OperationAmountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category can&apos;t be empty..
        /// </summary>
        public static string OperationCategoryRequired {
            get {
                return ResourceManager.GetString("OperationCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Name must be a string with a minimum length of 3 and a maximum length of 50..
        /// </summary>
        public static string OperationNameLength {
            get {
                return ResourceManager.GetString("OperationNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name field is required..
        /// </summary>
        public static string OperationNameRequired {
            get {
                return ResourceManager.GetString("OperationNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID.
        /// </summary>
        public static string Request_ID {
            get {
                return ResourceManager.GetString("Request ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string Select_Category {
            get {
                return ResourceManager.GetString("Select Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Language.
        /// </summary>
        public static string Site_Language {
            get {
                return ResourceManager.GetString("Site Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string Sorry__there_s_nothing_at_this_address_ {
            get {
                return ResourceManager.GetString("Sorry, there\'s nothing at this address.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Start_Date {
            get {
                return ResourceManager.GetString("Start Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swapping to the Development environment displays detailed information about the error that occurred..
        /// </summary>
        public static string Swapping_to_the_Development_environment_displays_detailed_information_about_the_error_that_occurred_ {
            get {
                return ResourceManager.GetString("Swapping to the Development environment displays detailed information about the e" +
                        "rror that occurred.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Development environment shouldn&apos;t be enabled for deployed applications..
        /// </summary>
        public static string The_Development_environment_shouldn_t_be_enabled_for_deployed_applications_ {
            get {
                return ResourceManager.GetString("The Development environment shouldn\'t be enabled for deployed applications.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not authorized to reach this page. You need to log in..
        /// </summary>
        public static string You_re_not_authorized_to_reach_this_page__You_need_to_log_in_ {
            get {
                return ResourceManager.GetString("You\'re not authorized to reach this page. You need to log in.", resourceCulture);
            }
        }
    }
}
